# version: '3.9'

services:

  nginx:
    image: nginx #:1.19.8-alpine    
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app

  nginx-unprivileged:
    image: nginxinc/nginx-unprivileged
    container_name: nginx-unprivileged
    ports:
      - "8080:8080"
    volumes:
      - www-html:/var/www/html
      - ./nginx-unprivileged-conf.d:/etc/nginx-unprivileged/conf.d
      - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app

volumes:
  www-html:
  etc-letsencrypt:


networks:
  app:
    driver: bridge
