# version: '3.9'

services:

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email dmaslyaev42@gmail.com --agree-tos --no-eff-email -d nginxtest.ru

  nginx:
    image: nginx #:1.19.8-alpine    
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app

  nginx-unprivileged:
    image: nginxinc/nginx-unprivileged
    container_name: nginx-unprivileged
    ports:
      - "80:8080"
    volumes:
      - www-html:/var/www/html
      - ./nginx-unprivileged-conf.d:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app

volumes:
  www-html:
  etc-letsencrypt:


networks:
  app:
    driver: bridge
